backend:
  name: git-gateway
  branch: main # Branch to update (defaults to master)

# Publish mode option for editorial workflow
publish_mode: editorial_workflow

# Media folder where uploads will be stored
media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"

# Define common field patterns
site_page_fields: &site_page_fields
  - {label: "Layout", name: "layout", widget: "hidden", default: "page.njk"}
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Description", name: "description", widget: "string", required: false}
  - {label: "Body", name: "body", widget: "markdown"}

# Collections define the structure for content types
collections:
  # Individual important page collections
  - name: "main_pages"
    label: "Main Pages"
    files:
      - name: "about"
        label: "About"
        file: "src/about/index.md"
        fields: *site_page_fields

      - name: "contact"
        label: "Contact"
        file: "src/contact/index.md"
        fields: *site_page_fields

      - name: "exhibitions"
        label: "Exhibitions"
        file: "src/exhibitions/index.md"
        fields: *site_page_fields

      - name: "membership"
        label: "Membership"
        file: "src/membership/index.md"
        fields: *site_page_fields

      - name: "whats-on"
        label: "What's On"
        file: "src/whats-on/index.md" # Fixed typo in path (was 'whats-ao')
        fields: *site_page_fields

