backend:
  name: git-gateway
  branch: main # Branch to update (defaults to master)

# Publish mode option for editorial workflow
publish_mode: editorial_workflow

# Media folder where uploads will be stored
media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"

# Collections define the structure for content types
collections:
  - name: "pages"
    label: "Site Pages"
    folder: "src"
    create: true
    nested:
      depth: 100
      summary: "{{title}}"
    exclude: "_includes/**/*,_data/**/*,_11ty/**/*,assets/**/*,admin/**/*"
    include: "membership/index.md,about/index.md,contact/index.md,whats-on/index.md,exhibitions/index.md,learning/index.md"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}

  # Individual important page collections
  - name: "key_pages"
    label: "Key Pages"
    files:
      - name: "membership"
        label: "Membership Page"
        file: "src/membership/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

      - name: "about"
        label: "About Page"
        file: "src/about/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

      - name: "contact"
        label: "Contact Page"
        file: "src/contact/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

