backend:
  name: git-gateway
  branch: decap # Branch to update - using decap branch for testing
  site_url: https://devserver-decap--eps-website.netlify.app # Preview deployment URL

# Local backend for local development
local_backend: true

# Publish mode option for editorial workflow
publish_mode: editorial_workflow

# Media folder where uploads will be stored
media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"

# Collections define the structure for content types
collections:
  - name: "pages"
    label: "Pages"
    folder: "src"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}

  - name: "posts"
    label: "News & Updates"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Summary", name: "summary", widget: "text", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "events"
    label: "Events"
    folder: "src/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/event.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "eventDate", widget: "datetime"}
      - {label: "End Date", name: "endDate", widget: "datetime", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ["event"]}

  # Add more collections as needed

